version: '3.4'
services:
  db:
    container_name: ilios_mysql
    image: ilios/mysql-demo
  webapp:
    container_name: ilios_apache_php
    image: ilios/ilios-apache-php
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    environment:
      - ILIOS_API_ENVIRONMENT=dev
      - ILIOS_API_DEBUG=true
      - ILIOS_DATABASE_HOST=db
    expose:
      - "9000"
    volumes:
      - ./:/var/www/ilios:delegated
