version: '3.4'
services:
  db:
    container_name: ilios_mysql
    image: ilios/mysql-demo
  webapp:
    container_name: ilios_apache_php
    image: ilios/ilios-apache-php
    ports:
      - "80:80"
      - "443:443"

