security:
    access_decision_manager:
      allow_if_all_abstain: false
      strategy: unanimous
    firewalls:
        api_docs:
            pattern:   ^/api/doc
            anonymous: ~
        anonymous_auth:
            pattern:    ^/(auth|application)/(login|config|logout)
            anonymous: ~
        authenticated_auth:
            pattern:    ^/auth
            stateless: true
            simple_preauth:
                authenticator: Ilios\AuthenticationBundle\Service\JsonWebTokenAuthenticator
            provider: session_user
        authenticated_application:
            pattern:    ^/application
            stateless: true
            simple_preauth:
                authenticator: Ilios\AuthenticationBundle\Service\JsonWebTokenAuthenticator
            provider: session_user
        upload:
            pattern:    ^/upload
            stateless: true
            simple_preauth:
                authenticator: Ilios\AuthenticationBundle\Service\JsonWebTokenAuthenticator
            provider: session_user
        errors:
            pattern:    ^/errors
            stateless: true
            simple_preauth:
                authenticator: Ilios\AuthenticationBundle\Service\JsonWebTokenAuthenticator
            provider: session_user
        default:
            pattern:    ^/api
            stateless: true
            simple_preauth:
                authenticator: Ilios\AuthenticationBundle\Service\JsonWebTokenAuthenticator
            provider: session_user
    providers:
        session_user:
            id: Ilios\AuthenticationBundle\Service\SessionUserProvider
